import { Wallet } from "@/src/utils/WalletContext";
import "./globals.css";
import Provider from "next-auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Wallet>
        <body>{children}</body>
      </Wallet>
    </html>
  );
}
